CREATE TABLE users (
id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
username VARCHAR(20) NOT NULL,
passwordhash BINARY(18) NOT NULL,
realname VARCHAR(20) NOT NULL,
birthday DATE NOT NULL,
salt BINARY(24) NOT NULL,
street VARCHAR(20),
street_nr INTEGER,
zipcode VARCHAR(10),
city VARCHAR(20),
country VARCHAR(20)
);
